services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - 4444:4444
  brick-blot-bot:
    container_name: brick-blot-bot
    build: .
    image: registry.digitalocean.com/mushroom-kingdom/brick-blot-bot:latest
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - API=${API}
      - API_SECRET=${API_SECRET}
    depends_on:
      - "selenium"
