services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:latest
    shm_size: 2g
  brick-blot-bot:
    container_name: brick-blot-bot
    build: .
    image: registry.digitalocean.com/mushroom-kingdom/brick-blot-bot:latest
    depends_on:
      - "selenium"
