services:
  hub:
    image: selenium/hub
    ports:
      - '4444:4444'
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:4444/grid/api/proxy']
      interval: 10s
      timeout: 5s
      retries: 3
  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:5555']
      interval: 10s
      timeout: 5s
      retries: 3

  brick-blot-bot:
    container_name: brick-blot-bot
    build: .
    image: registry.digitalocean.com/mushroom-kingdom/brick-blot-bot:latest
    env_file:
      - ./.env
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - API=${API}
      - API_SECRET=${API_SECRET}
