name: "Post reports to X"

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  post:
    name: "Post new reports to X"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trunk
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run brick-blot-bot
        env:
          CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
          CONSUMER_KEY_SECRET: ${{secrets.CONSUMER_KEY_SECRET}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        run: python brick-blot-bot

      - name: Commit database changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "🗃️ Save reports"
          add: "reports.db"
